# Generated by Django 3.1 on 2020-09-05 07:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onam_chitty', '0003_auto_20200905_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='price_given',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10000), django.core.validators.MinValueValidator(10)]),
        ),
    ]
