# Generated by Django 3.1 on 2020-09-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onam_chitty', '0004_auto_20200905_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='price_given',
            field=models.PositiveIntegerField(),
        ),
    ]
