# Generated by Django 3.1.1 on 2020-09-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onam_chitty', '0007_auto_20200907_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
